version: '3.8'

services:
  api:
    build: .
    container_name: node-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    command: npm run dev
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mynetwork

  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    environment: 
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge